spring:
  datasource:
    url: jdbc:p6spy:h2:mem:myapp
    username: sa
    password:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect