spring:
  datasource:
#    url: jdbc:h2:./testdb;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:./testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect